# Generated by Django 5.1.7 on 2025-04-02 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_description_review_comment_remove_review_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
